import type { Copy, Locale, Project } from "@/lib/types";

export const COPY: Record<Locale, Copy> = {
  fa: {
    dir: "rtl",
    nav: { home: "خانه", about: "درباره", work: "نمونه‌کارها", services: "تعرفه", contact: "تماس" },
    eyebrow: "طراح UI/UX",
    hiPrefix: "سلام، من",
    name: "فاطمه غفاری",
    tagline: "طراح UI/UX که تجربهٔ کاربری را به نتیجهٔ قابل‌اندازه‌گیری برای کسب‌وکار تبدیل می‌کند.",
    sub: "از پژوهش و معماری اطلاعات تا سیستم طراحی و هندآف؛ محصولاتی می‌سازم که کاربر راحت‌تر استفاده می‌کند و تیم محصول سریع‌تر شیپ می‌کند.",
    ctaContact: "بیایید صحبت کنیم",
    ctaWork: "نمونه‌کارها",
    badgeAvailable: "آمادهٔ همکاری تمام‌وقت و پروژه‌ای",
    badgeTool: "طراحی‌شده در فیگما",
    canvasTitle: "artboard.fig",
    layers: ["هدر", "بخش قهرمان", "کارت‌های ویژگی", "فوتر"],
    marquee: ["پژوهش کاربر", "وایرفریم", "پروتوتایپ", "سیستم طراحی", "تست کاربردپذیری", "فیگما", "هندآف"],
    aboutEyebrow: "درباره من",
    aboutTitle: "طراحی یعنی حل مسئله، نه فقط چیدن رنگ و فونت",
    aboutBody:
      "چند سالی است روی محصولات دیجیتال کار می‌کنم؛ از تحقیق کاربر و وایرفریم تا پروتوتایپ‌های تعاملی و سیستم‌های طراحی منسجم. تمرکز اصلی‌ام روی UI/UX است، ولی چون زبان فرانت‌اند را هم بلدم (React، Next.js، Tailwind)، طرح‌هایم همیشه با واقعیت پیاده‌سازی هماهنگ است.",
    expertiseEyebrow: "تخصص",
    expertiseTitle: "دقیقاً چه کاری انجام می‌دهم",
    expertise: [
      { icon: "research", t: "پژوهش و استراتژی محصول", d: "مصاحبه با کاربر، تحلیل رقبا و تبدیل یافته‌ها به تصمیم‌های طراحی قابل‌دفاع" },
      { icon: "design", t: "طراحی رابط کاربری (UI)", d: "از وایرفریم تا پروتوتایپ تعاملی، با دقت پیکسلی در فیگما" },
      { icon: "system", t: "سیستم طراحی (Design System)", d: "کتابخانهٔ کامپوننت مقیاس‌پذیر برای هماهنگی تیم‌های چندنفره" },
      { icon: "handoff", t: "هندآف و همکاری با توسعه", d: "مستندسازی دقیق و هماهنگی مستقیم با تیم فرانت‌اند (React / Next.js)" },
    ],
    servicesEyebrow: "تعرفه و خدمات",
    servicesTitle: "چطور می‌تونیم همکاری کنیم",
    servicesSub: "چند بستهٔ رایج — بسته به دامنهٔ واقعی پروژه‌ات با هم دقیق‌ترش می‌کنیم.",
    servicesTeaser: "پکیج‌های طراحی، از یک مشاورهٔ کوتاه تا طراحی کامل محصول.",
    seeServices: "مشاهدهٔ تعرفه و خدمات",
    servicesPageTitle: "تعرفه و خدمات",
    servicesPageSub: "این‌ها نقطهٔ شروع رایجن، نه قیمت ثابت — چون هر پروژه دامنهٔ خودش رو داره. بعد از شنیدن جزئیات کارت، یک برآورد واقعی و شفاف بهت می‌دم.",
    servicesNote: "قیمت دقیق بعد از یک مکالمهٔ کوتاه دربارهٔ دامنهٔ پروژه مشخص می‌شه.",
    services: [
      {
        title: "مشاورهٔ UX / بازبینی محصول",
        desc: "بررسی یک محصول یا جریان موجود و ارائهٔ یک گزارش عملی از مشکلات و پیشنهادها.",
        features: ["بازبینی heuristics", "یادداشت‌های قابلیت استفاده", "گزارش اولویت‌بندی‌شده"],
      },
      {
        title: "طراحی UI/UX (وب یا اپ)",
        desc: "از وایرفریم تا پروتوتایپ تعاملی با دقت پیکسلی، آمادهٔ هندآف به تیم توسعه.",
        features: ["پژوهش کاربر", "وایرفریم و معماری اطلاعات", "پروتوتایپ تعاملی در فیگما"],
      },
      {
        title: "سیستم طراحی",
        desc: "کتابخانهٔ کامپوننت مقیاس‌پذیر که تیم‌های چندنفره رو هماهنگ نگه می‌داره.",
        features: ["توکن‌های طراحی", "کتابخانهٔ کامپوننت در فیگما", "مستندسازی برای توسعه"],
      },
    ],
    serviceCta: "درخواست قیمت",
    processEyebrow: "روند کار",
    processTitle: "از ایده تا هندآف",
    process: [
      { t: "کشف و پژوهش", d: "فهم کاربر، رقبا و محدودیت‌های کسب‌وکار" },
      { t: "وایرفریم", d: "ساختار اطلاعات و جریان کاربر" },
      { t: "پروتوتایپ", d: "طراحی بصری و تعامل در فیگما" },
      { t: "تست کاربردپذیری", d: "اعتبارسنجی با کاربران واقعی" },
      { t: "هندآف به توسعه", d: "مستندسازی برای تیم فرانت‌اند" },
    ],
    workEyebrow: "نمونه‌کارها",
    workTitle: "چند پروژهٔ منتخب",
    workAll: "همهٔ پروژه‌ها",
    seeAll: "مشاهدهٔ همهٔ نمونه‌کارها",
    workPageTitle: "همهٔ نمونه‌کارها",
    workPageSub: "پروژه‌هایی که روی آن‌ها کار کرده‌ام — از پژوهش تا طراحی نهایی.",
    filterAll: "همه",
    searchPlaceholder: "جستجو در نمونه‌کارها…",
    noResults: "چیزی پیدا نشد. کلمهٔ دیگری امتحان کن یا فیلتر را پاک کن.",
    loadMore: "نمایش بیشتر",
    detailBack: "بازگشت به همهٔ نمونه‌کارها",
    detailViewLive: "مشاهدهٔ آنلاین",
    detailViewCode: "مشاهدهٔ کد",
    detailDescPlaceholder: "توضیحات این پروژه به‌زودی اضافه می‌شود.",
    detailNotFound: "این پروژه پیدا نشد.",
    workLoading: "در حال بارگذاری نمونه‌کارها…",
    workFallback: "نمونه‌کارها فعلاً از دریبل قابل مشاهده‌ست:",
    viewCase: "مشاهده",
    viewDribbble: "مشاهدهٔ همهٔ کارها در دریبل",
    linksEyebrow: "ارتباط",
    linksTitle: "بیایید کاری با هم بسازیم",
    linksSub: "چه یک پروژهٔ کامل داری چه فقط می‌خوای سلام کنی — پیامت رو مستقیم می‌بینم.",
    portfolio: "پورتفولیو", resume: "رزومه",
    nextEyebrow: "بعدش چی می‌شه",
    nextTitle: "از پیام تا شروع همکاری",
    nextSteps: [
      { t: "پیامت رو می‌فرستی", d: "فرم رو پر می‌کنی یا مستقیم توی شبکه‌های اجتماعی پیام می‌دی" },
      { t: "جواب می‌دم", d: "دربارهٔ پروژه و نیازت بیشتر می‌پرسم" },
      { t: "شروع می‌کنیم", d: "زمان‌بندی و جزئیات همکاری رو مشخص می‌کنیم" },
    ],
    faqEyebrow: "سوالات متداول",
    faqTitle: "چیزهایی که معمولاً می‌پرسن",
    faq: [
      { q: "چه خدماتی ارائه می‌دی؟", a: "پژوهش کاربر، طراحی UI، سیستم طراحی، پروتوتایپ تعاملی، و هندآف به تیم توسعه — از صفر تا محصول قابل‌اجرا." },
      { q: "با تیم‌های خارج از ایران هم همکاری می‌کنی؟", a: "بله، به‌صورت ریموت با تیم‌ها و کارفرماهای بین‌المللی هم کار می‌کنم." },
      { q: "با چه ابزارهایی کار می‌کنی؟", a: "فیگما برای طراحی، و چون زبان فرانت‌اند (React، Next.js، Tailwind) رو هم بلدم، طرح‌هام همیشه با واقعیت پیاده‌سازی هماهنگه." },
      { q: "برای همکاری تمام‌وقت هم در دسترسی؟", a: "بله، هم برای همکاری تمام‌وقت و هم پروژه‌ای/فریلنس در دسترسم." },
      { q: "یک پروژهٔ معمولی چقدر طول می‌کشه؟", a: "بستگی به دامنهٔ پروژه داره — بعد از شنیدن جزئیات کارت، یک برآورد واقعی بهت می‌دم." },
    ],
    formName: "نام", formEmail: "ایمیل", formMsg: "پیام‌تان",
    formSend: "ارسال پیام", formSending: "در حال ارسال…", formOk: "پیام شما ارسال شد. زودی جواب می‌دم!",
    formErr: "چیزی درست پیش نرفت. لطفاً دوباره تلاش کنید یا مستقیم ایمیل بزنید.",
    formErrRequired: "این فیلد الزامی است",
    formErrEmail: "ایمیل معتبر نیست",
    back: "بازگشت به خانه",
    footer: "تمامی حقوق محفوظ است",
    made: "طراحی و ساخته‌شده توسط فاطمه",
  },
  en: {
    dir: "ltr",
    nav: { home: "Home", about: "About", work: "Work", services: "Pricing", contact: "Contact" },
    eyebrow: "UI/UX Designer",
    hiPrefix: "Hi, I'm",
    name: "Fateme Ghafari",
    tagline: "UI/UX Designer who turns user experience into measurable business results.",
    sub: "From research and information architecture to design systems and dev handoff — I build products people find easy to use and teams ship faster.",
    ctaContact: "Let's talk",
    ctaWork: "See work",
    badgeAvailable: "Open to full-time & freelance work",
    badgeTool: "Designed in Figma",
    canvasTitle: "artboard.fig",
    layers: ["Header", "Hero section", "Feature cards", "Footer"],
    marquee: ["User Research", "Wireframing", "Prototyping", "Design Systems", "Usability Testing", "Figma", "Handoff"],
    aboutEyebrow: "About",
    aboutTitle: "Design is problem-solving, not just picking colors and fonts",
    aboutBody:
      "I've spent the last few years on digital products — user research, wireframes, interactive prototypes and design systems that hold together. UI/UX is where I live, but since I also speak front-end (React, Next.js, Tailwind), what I design stays honest to what can actually ship.",
    expertiseEyebrow: "Expertise",
    expertiseTitle: "What I actually do",
    expertise: [
      { icon: "research", t: "Research & Product Strategy", d: "User interviews, competitive analysis, and turning findings into defensible design decisions" },
      { icon: "design", t: "UI Design", d: "Wireframes through pixel-accurate interactive prototypes in Figma" },
      { icon: "system", t: "Design Systems", d: "Scalable component libraries that keep multi-person product teams aligned" },
      { icon: "handoff", t: "Handoff & Dev Collaboration", d: "Precise documentation and direct coordination with front-end teams (React / Next.js)" },
    ],
    servicesEyebrow: "Pricing & Services",
    servicesTitle: "Ways we can work together",
    servicesSub: "A few common packages — scoped precisely once I know your actual project.",
    servicesTeaser: "Design packages, from a quick consult to full product design.",
    seeServices: "See pricing & services",
    servicesPageTitle: "Pricing & Services",
    servicesPageSub: "These are common starting points, not fixed prices — every project's scope is different. Once I hear the details, I'll give you a realistic, transparent estimate.",
    servicesNote: "Exact pricing is worked out after a short conversation about project scope.",
    services: [
      {
        title: "UX Consultation / Audit",
        desc: "A review of an existing product or flow, with an actionable report on what's working and what isn't.",
        features: ["Heuristic review", "Usability notes", "Prioritized report"],
      },
      {
        title: "UI/UX Design (Web or App)",
        desc: "From wireframes to pixel-accurate interactive prototypes, ready for dev handoff.",
        features: ["User research", "Wireframes & information architecture", "Interactive prototype in Figma"],
      },
      {
        title: "Design System",
        desc: "A scalable component library that keeps multi-person teams aligned.",
        features: ["Design tokens", "Component library in Figma", "Documentation for developers"],
      },
    ],
    serviceCta: "Request a quote",
    processEyebrow: "Process",
    processTitle: "From idea to handoff",
    process: [
      { t: "Discover & Research", d: "Understanding users, competitors, constraints" },
      { t: "Wireframe", d: "Information structure and user flow" },
      { t: "Prototype", d: "Visual design and interaction in Figma" },
      { t: "Usability Testing", d: "Validating with real users" },
      { t: "Handoff", d: "Documentation for the front-end team" },
    ],
    workEyebrow: "Selected Work",
    workTitle: "A few featured projects",
    workAll: "All projects",
    seeAll: "See all work",
    workPageTitle: "All Work",
    workPageSub: "Projects I've worked on — from research to final design.",
    filterAll: "All",
    searchPlaceholder: "Search projects…",
    noResults: "Nothing matched. Try a different term or clear the filter.",
    loadMore: "Load more",
    detailBack: "Back to all work",
    detailViewLive: "View live",
    detailViewCode: "View code",
    detailDescPlaceholder: "Case study details coming soon.",
    detailNotFound: "This project couldn't be found.",
    workLoading: "Loading projects…",
    workFallback: "See the full case studies on Dribbble for now:",
    viewCase: "View",
    viewDribbble: "See all work on Dribbble",
    linksEyebrow: "Connect",
    linksTitle: "Let's build something together",
    linksSub: "Whether it's a full project or just a hello — your message reaches me directly.",
    portfolio: "Portfolio", resume: "Resume",
    nextEyebrow: "What happens next",
    nextTitle: "From message to kickoff",
    nextSteps: [
      { t: "You send a message", d: "Fill out the form, or reach out directly on social media" },
      { t: "I get back to you", d: "I'll ask a few questions about the project and what you need" },
      { t: "We get started", d: "We lock in a timeline and the details of working together" },
    ],
    faqEyebrow: "FAQ",
    faqTitle: "Things people usually ask",
    faq: [
      { q: "What services do you offer?", a: "User research, UI design, design systems, interactive prototyping, and handoff to the dev team — from zero to a shippable product." },
      { q: "Do you work with teams outside your country?", a: "Yes, I work remotely with international teams and clients." },
      { q: "What tools do you use?", a: "Figma for design — and since I also speak front-end (React, Next.js, Tailwind), what I design stays honest to what can actually ship." },
      { q: "Are you open to full-time roles?", a: "Yes, I'm open to both full-time and freelance/project-based work." },
      { q: "How long does a typical project take?", a: "It depends on scope — once I hear the details, I'll give you a realistic estimate." },
    ],
    formName: "Name", formEmail: "Email", formMsg: "Your message",
    formSend: "Send message", formSending: "Sending…", formOk: "Message sent — I'll get back to you soon!",
    formErr: "Something went wrong. Please retry or email me directly.",
    formErrRequired: "This field is required",
    formErrEmail: "Enter a valid email",
    back: "Back to home",
    footer: "All rights reserved",
    made: "Designed & built by Fateme",
  },
  ko: {
    dir: "ltr",
    nav: { home: "홈", about: "소개", work: "작업", services: "요금", contact: "연락처" },
    eyebrow: "UI/UX 디자이너",
    hiPrefix: "안녕하세요, 저는",
    name: "Fateme Ghafari",
    tagline: "사용자 경험을 측정 가능한 비즈니스 성과로 만드는 UI/UX 디자이너입니다.",
    sub: "리서치와 정보 구조 설계부터 디자인 시스템과 개발 핸드오프까지 — 사용자가 편하게 쓰고 팀이 더 빠르게 출시할 수 있는 제품을 만듭니다.",
    ctaContact: "연락하기",
    ctaWork: "작업 보기",
    badgeAvailable: "정규직 및 프리랜스 협업 가능",
    badgeTool: "Figma로 디자인함",
    canvasTitle: "artboard.fig",
    layers: ["헤더", "히어로 섹션", "기능 카드", "푸터"],
    marquee: ["사용자 리서치", "와이어프레임", "프로토타입", "디자인 시스템", "사용성 테스트", "Figma", "핸드오프"],
    aboutEyebrow: "소개",
    aboutTitle: "디자인은 색과 폰트를 고르는 일이 아니라 문제를 푸는 일입니다",
    aboutBody:
      "지난 몇 년간 디지털 제품을 만들어왔습니다 — 사용자 리서치, 와이어프레임, 인터랙티브 프로토타입, 그리고 탄탄한 디자인 시스템까지. 중심은 UI/UX지만 프론트엔드(React, Next.js, Tailwind)도 다룰 줄 알아서, 제 디자인은 언제나 실제 구현과 맞닿아 있습니다.",
    expertiseEyebrow: "전문 분야",
    expertiseTitle: "제가 실제로 하는 일",
    expertise: [
      { icon: "research", t: "리서치 & 제품 전략", d: "사용자 인터뷰, 경쟁사 분석, 그리고 인사이트를 설득력 있는 디자인 결정으로 전환" },
      { icon: "design", t: "UI 디자인", d: "와이어프레임부터 픽셀 단위의 인터랙티브 프로토타입까지, Figma에서" },
      { icon: "system", t: "디자인 시스템", d: "여러 명이 함께 작업하는 제품 팀을 위한 확장 가능한 컴포넌트 라이브러리" },
      { icon: "handoff", t: "핸드오프 & 개발 협업", d: "정확한 문서화와 프론트엔드 팀(React / Next.js)과의 직접적인 협업" },
    ],
    servicesEyebrow: "요금 & 서비스",
    servicesTitle: "함께 일하는 방법",
    servicesSub: "몇 가지 대표적인 패키지입니다 — 실제 프로젝트 내용을 들은 뒤 정확히 범위를 정합니다.",
    servicesTeaser: "간단한 컨설팅부터 전체 제품 디자인까지, 디자인 패키지를 소개합니다.",
    seeServices: "요금 & 서비스 보기",
    servicesPageTitle: "요금 & 서비스",
    servicesPageSub: "아래는 고정 가격이 아니라 일반적인 시작점입니다 — 프로젝트마다 범위가 다르기 때문입니다. 자세한 내용을 들은 후 현실적이고 투명한 견적을 드립니다.",
    servicesNote: "정확한 가격은 프로젝트 범위에 대한 짧은 대화 후에 정해집니다.",
    services: [
      {
        title: "UX 컨설팅 / 진단",
        desc: "기존 제품이나 플로우를 검토하고, 실행 가능한 개선 리포트를 제공합니다.",
        features: ["휴리스틱 검토", "사용성 노트", "우선순위가 정리된 리포트"],
      },
      {
        title: "UI/UX 디자인 (웹 또는 앱)",
        desc: "와이어프레임부터 픽셀 단위의 인터랙티브 프로토타입까지, 개발 핸드오프 준비 완료.",
        features: ["사용자 리서치", "와이어프레임 & 정보 구조", "Figma 인터랙티브 프로토타입"],
      },
      {
        title: "디자인 시스템",
        desc: "여러 명이 함께 작업하는 팀을 위한 확장 가능한 컴포넌트 라이브러리.",
        features: ["디자인 토큰", "Figma 컴포넌트 라이브러리", "개발자를 위한 문서화"],
      },
    ],
    serviceCta: "견적 요청하기",
    processEyebrow: "작업 방식",
    processTitle: "아이디어에서 핸드오프까지",
    process: [
      { t: "발견 & 리서치", d: "사용자, 경쟁사, 제약 조건 파악" },
      { t: "와이어프레임", d: "정보 구조와 사용자 흐름" },
      { t: "프로토타입", d: "Figma에서의 비주얼 디자인과 인터랙션" },
      { t: "사용성 테스트", d: "실제 사용자로 검증" },
      { t: "핸드오프", d: "프론트엔드 팀을 위한 문서화" },
    ],
    workEyebrow: "대표 작업",
    workTitle: "선정된 프로젝트",
    workAll: "모든 프로젝트",
    seeAll: "모든 작업 보기",
    workPageTitle: "전체 작업",
    workPageSub: "리서치부터 최종 디자인까지, 작업한 프로젝트들입니다.",
    filterAll: "전체",
    searchPlaceholder: "프로젝트 검색…",
    noResults: "일치하는 항목이 없습니다. 다른 단어로 검색하거나 필터를 지워보세요.",
    loadMore: "더 보기",
    detailBack: "전체 작업으로 돌아가기",
    detailViewLive: "라이브로 보기",
    detailViewCode: "코드 보기",
    detailDescPlaceholder: "케이스 스터디 설명은 곧 추가될 예정입니다.",
    detailNotFound: "이 프로젝트를 찾을 수 없습니다.",
    workLoading: "프로젝트를 불러오는 중…",
    workFallback: "지금은 Dribbble에서 전체 작업을 확인하세요:",
    viewCase: "보기",
    viewDribbble: "Dribbble에서 모든 작업 보기",
    linksEyebrow: "연결",
    linksTitle: "함께 무언가를 만들어봐요",
    linksSub: "프로젝트든 가벼운 인사든, 메시지는 저에게 바로 전달됩니다.",
    portfolio: "포트폴리오", resume: "이력서",
    nextEyebrow: "다음 단계",
    nextTitle: "메시지부터 시작까지",
    nextSteps: [
      { t: "메시지를 보내주세요", d: "폼을 작성하거나 소셜 미디어로 바로 연락하세요" },
      { t: "답장을 드립니다", d: "프로젝트와 필요한 사항에 대해 몇 가지 여쭤볼게요" },
      { t: "함께 시작해요", d: "일정과 협업 세부사항을 정합니다" },
    ],
    faqEyebrow: "자주 묻는 질문",
    faqTitle: "많이 받는 질문들",
    faq: [
      { q: "어떤 서비스를 제공하나요?", a: "사용자 리서치, UI 디자인, 디자인 시스템, 인터랙티브 프로토타입, 그리고 개발팀으로의 핸드오프까지 — 처음부터 실제로 출시 가능한 제품까지." },
      { q: "해외 팀과도 협업하나요?", a: "네, 해외 팀 및 클라이언트와도 원격으로 협업합니다." },
      { q: "어떤 툴을 사용하나요?", a: "디자인은 Figma를 사용하고, 프론트엔드(React, Next.js, Tailwind)도 다룰 줄 알아서 제 디자인은 언제나 실제 구현과 맞닿아 있습니다." },
      { q: "정규직 포지션도 고려하나요?", a: "네, 정규직과 프리랜스/프로젝트 단위 협업 모두 열려 있습니다." },
      { q: "일반적으로 프로젝트는 얼마나 걸리나요?", a: "범위에 따라 다릅니다 — 자세한 내용을 들은 후 현실적인 예상 기간을 알려드릴게요." },
    ],
    formName: "이름", formEmail: "이메일", formMsg: "메시지",
    formSend: "메시지 보내기", formSending: "전송 중…", formOk: "메시지가 전송되었습니다. 곧 답장할게요!",
    formErr: "문제가 발생했습니다. 다시 시도하거나 이메일로 연락해주세요.",
    formErrRequired: "필수 항목입니다",
    formErrEmail: "유효한 이메일을 입력하세요",
    back: "홈으로",
    footer: "All rights reserved",
    made: "Fateme가 디자인하고 만들었습니다",
  },
};

export const FONT_STACK: Record<Locale, string> = {
  fa: "'Vazirmatn', Tahoma, sans-serif",
  en: "'Inter', 'Vazirmatn', sans-serif",
  ko: "'Noto Sans KR', 'Inter', sans-serif",
};

export const DRIBBBLE_URL = "https://dribbble.com/fatemeweb";

export const SOCIALS_ICONS = ["github", "linkedin", "instagram", "send", "dribbble"];

export const PROJECTS_API = "https://new-personal-api.vercel.app";
export const PROJECTS_ENDPOINTS = ["PortfoliosData", "portfoliosdata", "projects", "works", "portfolio"];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function normalizeProject(item: any, i: number): Project {
  return {
    id: item.id ?? i,
    title: item.title || item.name || item.projectName || `Project ${i + 1}`,
    // Reserved for the case-study write-up you're planning to add to the API later —
    // works today with any of these field names, and simply stays hidden until filled in.
    desc: item.description || item.desc || item.summary || item.subtitle || "",
    category: item.category || item.tag || item.type || item.role || "",
    tags: Array.isArray(item.tags) ? item.tags : [],
    image: item.imgUrl || item.image || item.thumbnail || item.img || item.cover || item.thumbnailUrl || null,
    onlineLink: item.onlineLink || item.link || item.url || item.href || item.dribbbleUrl || null,
    gitLink: item.gitLink || item.githubLink || item.repo || null,
  };
}

export const WORK_TINTS = ["#007BFF", "#0B63C9", "#3D9CFF", "#6B7280", "#2563EB", "#4C8DFF", "#60A5FA", "#1D4ED8"];
