import type { Copy, Locale, Project } from "@/lib/types";

export const COPY: Record<Locale, Copy> = {
  fa: {
    dir: "rtl",
    nav: { home: "خانه", about: "درباره", work: "نمونه‌کارها", contact: "تماس" },
    eyebrow: "طراح UI/UX",
    hiPrefix: "سلام، من",
    name: "فاطمه غفاری",
    tagline: "طراح UI/UX که تجربهٔ کاربری را به نتیجهٔ قابل‌اندازه‌گیری برای کسب‌وکار تبدیل می‌کند.",
    sub: "از پژوهش و معماری اطلاعات تا سیستم طراحی و هندآف؛ محصولاتی می‌سازم که کاربر راحت‌تر استفاده می‌کند و تیم محصول سریع‌تر شیپ می‌کند.",
    ctaContact: "بیایید صحبت کنیم",
    ctaWork: "نمونه‌کارها",
    badgeAvailable: "آمادهٔ همکاری تمام‌وقت و پروژه‌ای",
    badgeTool: "طراحی‌شده در فیگما",
    canvasTitle: "artboard.fig",
    layers: ["هدر", "بخش قهرمان", "کارت‌های ویژگی", "فوتر"],
    marquee: ["پژوهش کاربر", "وایرفریم", "پروتوتایپ", "سیستم طراحی", "تست کاربردپذیری", "فیگما", "هندآف"],
    aboutEyebrow: "درباره من",
    aboutTitle: "طراحی یعنی حل مسئله، نه فقط چیدن رنگ و فونت",
    aboutBody:
      "چند سالی است روی محصولات دیجیتال کار می‌کنم؛ از تحقیق کاربر و وایرفریم تا پروتوتایپ‌های تعاملی و سیستم‌های طراحی منسجم. تمرکز اصلی‌ام روی UI/UX است، ولی چون زبان فرانت‌اند را هم بلدم (React، Next.js، Tailwind)، طرح‌هایم همیشه با واقعیت پیاده‌سازی هماهنگ است.",
    expertiseEyebrow: "تخصص",
    expertiseTitle: "دقیقاً چه کاری انجام می‌دهم",
    expertise: [
      { icon: "research", t: "پژوهش و استراتژی محصول", d: "مصاحبه با کاربر، تحلیل رقبا و تبدیل یافته‌ها به تصمیم‌های طراحی قابل‌دفاع" },
      { icon: "design", t: "طراحی رابط کاربری (UI)", d: "از وایرفریم تا پروتوتایپ تعاملی، با دقت پیکسلی در فیگما" },
      { icon: "system", t: "سیستم طراحی (Design System)", d: "کتابخانهٔ کامپوننت مقیاس‌پذیر برای هماهنگی تیم‌های چندنفره" },
      { icon: "handoff", t: "هندآف و همکاری با توسعه", d: "مستندسازی دقیق و هماهنگی مستقیم با تیم فرانت‌اند (React / Next.js)" },
    ],
    processEyebrow: "روند کار",
    processTitle: "از ایده تا هندآف",
    process: [
      { t: "کشف و پژوهش", d: "فهم کاربر، رقبا و محدودیت‌های کسب‌وکار" },
      { t: "وایرفریم", d: "ساختار اطلاعات و جریان کاربر" },
      { t: "پروتوتایپ", d: "طراحی بصری و تعامل در فیگما" },
      { t: "تست کاربردپذیری", d: "اعتبارسنجی با کاربران واقعی" },
      { t: "هندآف به توسعه", d: "مستندسازی برای تیم فرانت‌اند" },
    ],
    workEyebrow: "نمونه‌کارها",
    workTitle: "چند پروژهٔ منتخب",
    workAll: "همهٔ پروژه‌ها",
    seeAll: "مشاهدهٔ همهٔ نمونه‌کارها",
    workPageTitle: "همهٔ نمونه‌کارها",
    workPageSub: "پروژه‌هایی که روی آن‌ها کار کرده‌ام — از پژوهش تا طراحی نهایی.",
    filterAll: "همه",
    searchPlaceholder: "جستجو در نمونه‌کارها…",
    noResults: "چیزی پیدا نشد. کلمهٔ دیگری امتحان کن یا فیلتر را پاک کن.",
    loadMore: "نمایش بیشتر",
    detailBack: "بازگشت به همهٔ نمونه‌کارها",
    detailViewLive: "مشاهدهٔ آنلاین",
    detailViewCode: "مشاهدهٔ کد",
    detailDescPlaceholder: "توضیحات این پروژه به‌زودی اضافه می‌شود.",
    detailNotFound: "این پروژه پیدا نشد.",
    workLoading: "در حال بارگذاری نمونه‌کارها…",
    workFallback: "نمونه‌کارها فعلاً از دریبل قابل مشاهده‌ست:",
    viewCase: "مشاهده",
    viewDribbble: "مشاهدهٔ همهٔ کارها در دریبل",
    linksEyebrow: "ارتباط",
    linksTitle: "بیایید کاری با هم بسازیم",
    portfolio: "پورتفولیو", resume: "رزومه",
    formName: "نام", formEmail: "ایمیل", formMsg: "پیام‌تان",
    formSend: "ارسال پیام", formSending: "در حال ارسال…", formOk: "پیام شما ارسال شد. زودی جواب می‌دم!",
    formErr: "چیزی درست پیش نرفت. لطفاً دوباره تلاش کنید یا مستقیم ایمیل بزنید.",
    formErrRequired: "این فیلد الزامی است",
    formErrEmail: "ایمیل معتبر نیست",
    back: "بازگشت به خانه",
    footer: "تمامی حقوق محفوظ است",
    made: "طراحی و ساخته‌شده توسط فاطمه",
  },
  en: {
    dir: "ltr",
    nav: { home: "Home", about: "About", work: "Work", contact: "Contact" },
    eyebrow: "UI/UX Designer",
    hiPrefix: "Hi, I'm",
    name: "Fateme Ghafari",
    tagline: "UI/UX Designer who turns user experience into measurable business results.",
    sub: "From research and information architecture to design systems and dev handoff — I build products people find easy to use and teams ship faster.",
    ctaContact: "Let's talk",
    ctaWork: "See work",
    badgeAvailable: "Open to full-time & freelance work",
    badgeTool: "Designed in Figma",
    canvasTitle: "artboard.fig",
    layers: ["Header", "Hero section", "Feature cards", "Footer"],
    marquee: ["User Research", "Wireframing", "Prototyping", "Design Systems", "Usability Testing", "Figma", "Handoff"],
    aboutEyebrow: "About",
    aboutTitle: "Design is problem-solving, not just picking colors and fonts",
    aboutBody:
      "I've spent the last few years on digital products — user research, wireframes, interactive prototypes and design systems that hold together. UI/UX is where I live, but since I also speak front-end (React, Next.js, Tailwind), what I design stays honest to what can actually ship.",
    expertiseEyebrow: "Expertise",
    expertiseTitle: "What I actually do",
    expertise: [
      { icon: "research", t: "Research & Product Strategy", d: "User interviews, competitive analysis, and turning findings into defensible design decisions" },
      { icon: "design", t: "UI Design", d: "Wireframes through pixel-accurate interactive prototypes in Figma" },
      { icon: "system", t: "Design Systems", d: "Scalable component libraries that keep multi-person product teams aligned" },
      { icon: "handoff", t: "Handoff & Dev Collaboration", d: "Precise documentation and direct coordination with front-end teams (React / Next.js)" },
    ],
    processEyebrow: "Process",
    processTitle: "From idea to handoff",
    process: [
      { t: "Discover & Research", d: "Understanding users, competitors, constraints" },
      { t: "Wireframe", d: "Information structure and user flow" },
      { t: "Prototype", d: "Visual design and interaction in Figma" },
      { t: "Usability Testing", d: "Validating with real users" },
      { t: "Handoff", d: "Documentation for the front-end team" },
    ],
    workEyebrow: "Selected Work",
    workTitle: "A few featured projects",
    workAll: "All projects",
    seeAll: "See all work",
    workPageTitle: "All Work",
    workPageSub: "Projects I've worked on — from research to final design.",
    filterAll: "All",
    searchPlaceholder: "Search projects…",
    noResults: "Nothing matched. Try a different term or clear the filter.",
    loadMore: "Load more",
    detailBack: "Back to all work",
    detailViewLive: "View live",
    detailViewCode: "View code",
    detailDescPlaceholder: "Case study details coming soon.",
    detailNotFound: "This project couldn't be found.",
    workLoading: "Loading projects…",
    workFallback: "See the full case studies on Dribbble for now:",
    viewCase: "View",
    viewDribbble: "See all work on Dribbble",
    linksEyebrow: "Connect",
    linksTitle: "Let's build something together",
    portfolio: "Portfolio", resume: "Resume",
    formName: "Name", formEmail: "Email", formMsg: "Your message",
    formSend: "Send message", formSending: "Sending…", formOk: "Message sent — I'll get back to you soon!",
    formErr: "Something went wrong. Please retry or email me directly.",
    formErrRequired: "This field is required",
    formErrEmail: "Enter a valid email",
    back: "Back to home",
    footer: "All rights reserved",
    made: "Designed & built by Fateme",
  },
  ko: {
    dir: "ltr",
    nav: { home: "홈", about: "소개", work: "작업", contact: "연락처" },
    eyebrow: "UI/UX 디자이너",
    hiPrefix: "안녕하세요, 저는",
    name: "Fateme Ghafari",
    tagline: "사용자 경험을 측정 가능한 비즈니스 성과로 만드는 UI/UX 디자이너입니다.",
    sub: "리서치와 정보 구조 설계부터 디자인 시스템과 개발 핸드오프까지 — 사용자가 편하게 쓰고 팀이 더 빠르게 출시할 수 있는 제품을 만듭니다.",
    ctaContact: "연락하기",
    ctaWork: "작업 보기",
    badgeAvailable: "정규직 및 프리랜스 협업 가능",
    badgeTool: "Figma로 디자인함",
    canvasTitle: "artboard.fig",
    layers: ["헤더", "히어로 섹션", "기능 카드", "푸터"],
    marquee: ["사용자 리서치", "와이어프레임", "프로토타입", "디자인 시스템", "사용성 테스트", "Figma", "핸드오프"],
    aboutEyebrow: "소개",
    aboutTitle: "디자인은 색과 폰트를 고르는 일이 아니라 문제를 푸는 일입니다",
    aboutBody:
      "지난 몇 년간 디지털 제품을 만들어왔습니다 — 사용자 리서치, 와이어프레임, 인터랙티브 프로토타입, 그리고 탄탄한 디자인 시스템까지. 중심은 UI/UX지만 프론트엔드(React, Next.js, Tailwind)도 다룰 줄 알아서, 제 디자인은 언제나 실제 구현과 맞닿아 있습니다.",
    expertiseEyebrow: "전문 분야",
    expertiseTitle: "제가 실제로 하는 일",
    expertise: [
      { icon: "research", t: "리서치 & 제품 전략", d: "사용자 인터뷰, 경쟁사 분석, 그리고 인사이트를 설득력 있는 디자인 결정으로 전환" },
      { icon: "design", t: "UI 디자인", d: "와이어프레임부터 픽셀 단위의 인터랙티브 프로토타입까지, Figma에서" },
      { icon: "system", t: "디자인 시스템", d: "여러 명이 함께 작업하는 제품 팀을 위한 확장 가능한 컴포넌트 라이브러리" },
      { icon: "handoff", t: "핸드오프 & 개발 협업", d: "정확한 문서화와 프론트엔드 팀(React / Next.js)과의 직접적인 협업" },
    ],
    processEyebrow: "작업 방식",
    processTitle: "아이디어에서 핸드오프까지",
    process: [
      { t: "발견 & 리서치", d: "사용자, 경쟁사, 제약 조건 파악" },
      { t: "와이어프레임", d: "정보 구조와 사용자 흐름" },
      { t: "프로토타입", d: "Figma에서의 비주얼 디자인과 인터랙션" },
      { t: "사용성 테스트", d: "실제 사용자로 검증" },
      { t: "핸드오프", d: "프론트엔드 팀을 위한 문서화" },
    ],
    workEyebrow: "대표 작업",
    workTitle: "선정된 프로젝트",
    workAll: "모든 프로젝트",
    seeAll: "모든 작업 보기",
    workPageTitle: "전체 작업",
    workPageSub: "리서치부터 최종 디자인까지, 작업한 프로젝트들입니다.",
    filterAll: "전체",
    searchPlaceholder: "프로젝트 검색…",
    noResults: "일치하는 항목이 없습니다. 다른 단어로 검색하거나 필터를 지워보세요.",
    loadMore: "더 보기",
    detailBack: "전체 작업으로 돌아가기",
    detailViewLive: "라이브로 보기",
    detailViewCode: "코드 보기",
    detailDescPlaceholder: "케이스 스터디 설명은 곧 추가될 예정입니다.",
    detailNotFound: "이 프로젝트를 찾을 수 없습니다.",
    workLoading: "프로젝트를 불러오는 중…",
    workFallback: "지금은 Dribbble에서 전체 작업을 확인하세요:",
    viewCase: "보기",
    viewDribbble: "Dribbble에서 모든 작업 보기",
    linksEyebrow: "연결",
    linksTitle: "함께 무언가를 만들어봐요",
    portfolio: "포트폴리오", resume: "이력서",
    formName: "이름", formEmail: "이메일", formMsg: "메시지",
    formSend: "메시지 보내기", formSending: "전송 중…", formOk: "메시지가 전송되었습니다. 곧 답장할게요!",
    formErr: "문제가 발생했습니다. 다시 시도하거나 이메일로 연락해주세요.",
    formErrRequired: "필수 항목입니다",
    formErrEmail: "유효한 이메일을 입력하세요",
    back: "홈으로",
    footer: "All rights reserved",
    made: "Fateme가 디자인하고 만들었습니다",
  },
};

export const FONT_STACK: Record<Locale, string> = {
  fa: "'Vazirmatn', Tahoma, sans-serif",
  en: "'Inter', 'Vazirmatn', sans-serif",
  ko: "'Noto Sans KR', 'Inter', sans-serif",
};

export const DRIBBBLE_URL = "https://dribbble.com/fatemeweb";

export const SOCIALS_ICONS = ["github", "linkedin", "instagram", "send", "dribbble"];

export const PROJECTS_API = "https://new-personal-api.vercel.app";
export const PROJECTS_ENDPOINTS = ["PortfoliosData", "portfoliosdata", "projects", "works", "portfolio"];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function normalizeProject(item: any, i: number): Project {
  return {
    id: item.id ?? i,
    title: item.title || item.name || item.projectName || `Project ${i + 1}`,
    // Reserved for the case-study write-up you're planning to add to the API later —
    // works today with any of these field names, and simply stays hidden until filled in.
    desc: item.description || item.desc || item.summary || item.subtitle || "",
    category: item.category || item.tag || item.type || item.role || "",
    tags: Array.isArray(item.tags) ? item.tags : [],
    image: item.imgUrl || item.image || item.thumbnail || item.img || item.cover || item.thumbnailUrl || null,
    onlineLink: item.onlineLink || item.link || item.url || item.href || item.dribbbleUrl || null,
    gitLink: item.gitLink || item.githubLink || item.repo || null,
  };
}

export const WORK_TINTS = ["#007BFF", "#0B63C9", "#3D9CFF", "#6B7280", "#2563EB", "#4C8DFF", "#60A5FA", "#1D4ED8"];
